# Generated by Django 5.2.3 on 2025-07-24 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('experience_year', models.PositiveIntegerField()),
                ('price_per_minute', models.DecimalField(decimal_places=2, max_digits=6)),
                ('language_spoken', models.JSONField(default=list)),
                ('expertise', models.JSONField(default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='astrologer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
